Repository IUNO-TDM/MarketplaceCore, pull requests merged in 2018-08, with the labels that each got.

#208 pick right key of payment state change event
  MarketplaceCore-app/services/payment_service.js
Labels: in progress, refactoring

#212 bugfix for receiving payments
  MarketplaceCore-app/services/payment_service.js
Labels: bug, in progress, refactoring

#213 new testing
  MarketplaceCore-app/.gitignore
  MarketplaceCore-app/adapter/auth_service_adapter.js
  MarketplaceCore-app/app.js
  MarketplaceCore-app/config/config_defaults.js
  MarketplaceCore-app/database/function/license.js
  MarketplaceCore-app/database/function/report.js
  MarketplaceCore-app/database/model/component.js
  MarketplaceCore-app/database/model/technologydata.js
  MarketplaceCore-app/package-lock.json
  MarketplaceCore-app/package.json
  MarketplaceCore-app/routes/offers.js
  MarketplaceCore-app/routes/reports.js
  MarketplaceCore-app/routes/technologydata.js
  MarketplaceCore-app/schema/components_schema.js
  MarketplaceCore-app/schema/reports_schema.js
  MarketplaceCore-app/schema/technologydata_schema.js
  MarketplaceCore-app/services/brute_force_protection.js
  MarketplaceCore-app/services/content_type_validation.js
  MarketplaceCore-app/services/email_service.js
  MarketplaceCore-app/services/file_upload_handler.js
  MarketplaceCore-app/services/payment_service.js
  MarketplaceCore-app/services/query_parser.js
  database/README.md
  database/patches/data_scripts/iuno_marketplacecore_V0045V_data_0.sql
  database/patches/data_scripts/iuno_marketplacecore_V0045V_data_1.sql
  database/patches/data_scripts/iuno_marketplacecore_V0045V_data_3.sql
  database/patches/iuno_marketplacecore_V0045V_20180709.sql
  database/patches/iuno_marketplacecore_V0046V_20180712.sql
  database/patches/iuno_marketplacecore_V0047V_20180713.sql
  database/patches/iuno_marketplacecore_V0048V_20180723.sql
Labels: in progress

#214 Increased image size limit in schema validation for technology data …
  MarketplaceCore-app/schema/technologydata_schema.js
Labels: in progress

#216 Increased body limit
  MarketplaceCore-app/app.js
  MarketplaceCore-app/schema/technologydata_schema.js
Labels: in progress
